"""initial schema

Revision ID: 0532cf540095
Revises: 
Create Date: 2026-03-31 02:48:18.007250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0532cf540095'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('era_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('payer_name', sa.String(length=255), nullable=True),
    sa.Column('payer_id', sa.String(length=80), nullable=True),
    sa.Column('payee_name', sa.String(length=255), nullable=True),
    sa.Column('payee_npi', sa.String(length=20), nullable=True),
    sa.Column('total_actual_provider_payment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_method', sa.String(length=10), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('trace_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('era_file_id', sa.Integer(), nullable=True),
    sa.Column('patient_control_number', sa.String(length=50), nullable=True),
    sa.Column('claim_status_code', sa.String(length=2), nullable=True),
    sa.Column('is_denied', sa.Boolean(), nullable=True),
    sa.Column('total_charge_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('patient_responsibility', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('patient_first_name', sa.String(length=50), nullable=True),
    sa.Column('patient_last_name', sa.String(length=50), nullable=True),
    sa.Column('patient_member_id', sa.String(length=80), nullable=True),
    sa.Column('rendering_provider_npi', sa.String(length=20), nullable=True),
    sa.Column('statement_from_date', sa.Date(), nullable=True),
    sa.Column('statement_to_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['era_file_id'], ['era_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('procedure_code', sa.String(length=10), nullable=True),
    sa.Column('modifier', sa.String(length=10), nullable=True),
    sa.Column('charge_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('revenue_code', sa.String(length=10), nullable=True),
    sa.Column('units', sa.String(length=10), nullable=True),
    sa.Column('allowed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_line_id', sa.Integer(), nullable=True),
    sa.Column('group_code', sa.String(length=5), nullable=True),
    sa.Column('reason_code', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['service_line_id'], ['service_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adjustments')
    op.drop_table('service_lines')
    op.drop_table('claims')
    op.drop_table('era_files')
    # ### end Alembic commands ###
