"""Add payers table, update era_files and claims table

Revision ID: 4f66369d530f
Revises: 0532cf540095
Create Date: 2026-04-14 02:44:18.411134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f66369d530f'
down_revision: Union[str, Sequence[str], None] = '0532cf540095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payer_identifier', sa.String(length=80), nullable=False),
    sa.Column('payer_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payer_identifier')
    )
    op.add_column('claims', sa.Column('previous_claim_id', sa.Integer(), nullable=True))
    op.add_column('claims', sa.Column('payer_id', sa.Integer(), nullable=True))
    op.add_column('claims', sa.Column('is_current', sa.Boolean(), nullable=False))
    op.add_column('claims', sa.Column('final_payment_date', sa.Date(), nullable=True))
    op.alter_column('claims', 'patient_control_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key(None, 'claims', 'payers', ['payer_id'], ['id'])
    op.drop_column('era_files', 'payer_id')
    op.drop_column('era_files', 'filename')
    op.drop_column('era_files', 'payer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('era_files', sa.Column('payer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('era_files', sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('era_files', sa.Column('payer_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.alter_column('claims', 'patient_control_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('claims', 'final_payment_date')
    op.drop_column('claims', 'is_current')
    op.drop_column('claims', 'payer_id')
    op.drop_column('claims', 'previous_claim_id')
    op.drop_table('payers')
    # ### end Alembic commands ###
