"""Add pre submission claims

Revision ID: ba49c433ce9a
Revises: c30051fb0c91
Create Date: 2026-05-10 09:59:25.046089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba49c433ce9a'
down_revision: Union[str, Sequence[str], None] = 'c30051fb0c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_submission_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_identifier', sa.String(length=255), nullable=True),
    sa.Column('uploadedAt', sa.Date(), nullable=True),
    sa.Column('claim_type', sa.String(length=255), nullable=True),
    sa.Column('payer_type', sa.String(length=255), nullable=True),
    sa.Column('payer', sa.String(length=255), nullable=True),
    sa.Column('provider_specialty', sa.String(length=255), nullable=True),
    sa.Column('billing_provider', sa.String(length=255), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('claim_amount_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cpt_code', sa.String(length=255), nullable=True),
    sa.Column('modifier', sa.String(length=255), nullable=True),
    sa.Column('primary_icd10_dx', sa.String(length=255), nullable=True),
    sa.Column('secondary_dx_count', sa.Integer(), nullable=True),
    sa.Column('documentation_completeness', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('prior_auth_required', sa.Boolean(), nullable=True),
    sa.Column('prior_auth_obtained', sa.Boolean(), nullable=True),
    sa.Column('prior_auth_number', sa.String(length=255), nullable=True),
    sa.Column('denial_prediction', sa.Boolean(), nullable=True),
    sa.Column('denial_probability', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('denial_category', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_submission_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpt_code', sa.String(length=255), nullable=True),
    sa.Column('modifier', sa.String(length=255), nullable=True),
    sa.Column('pre_submission_claim_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pre_submission_claim_id'], ['pre_submission_claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('claims', sa.Column('created_at', sa.Date(), nullable=True))
    op.alter_column('era_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('era_files', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('claims', 'created_at')
    op.drop_table('pre_submission_services')
    op.drop_table('pre_submission_claims')
    # ### end Alembic commands ###
