"""Add is_first_pass column to claims

Revision ID: c30051fb0c91
Revises: 4f66369d530f
Create Date: 2026-04-27 20:47:32.468668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c30051fb0c91'
down_revision: Union[str, Sequence[str], None] = '4f66369d530f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('is_first_pass', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'is_first_pass')
    # ### end Alembic commands ###
