CARC_CODE_DESCRIPTIONS = {
    '2': 'Patient Responsibility',
    '4': 'Modifier inconsistency',
    '16': 'Claim lacks information',
    '18': 'Duplicate claim',
    '22': 'Coordination of benefits',
    '23': 'Already paid by other payer',
    '26': 'Prior to coverage effective date',
    '27': 'Expenses incurred after coverage terminated',
    '29': 'Timely filing expired',
    '45': 'Contractual adjustment',
    '49': 'Routine non-covered service',
    '50': 'Not medically necessary',
    '55': 'Procedure not appropriate for patient age/sex',
    '96': 'Non-covered charge',
    '97': 'Bundled into another service',
    '109': 'Claim not covered — refer to another payer',
    '119': 'Benefit maximum reached',
    '167': 'Diagnosis not covered',
    '170': 'Payment denied — precertification required',
    '197': 'Precertification/auth absent',
    'B7':  'Provider not certified',
    'B15': 'Service not authorized by provider',
    'MA04': 'Secondary payer info required',
}

CARC_CODE_ACTIONS = {
    '4': 'Resubmit w/ corrected modifier',
    '16': 'Resubmit with required data',
    '18': 'Investigate and resubmit if valid',
    '22': 'Send to secondary payer',
    '26': 'Verify enrollment, usually write-off',
    '27': 'Usually write-off',
    '29': 'Write off — verify appeal window',
    '45': 'Expected write-off',
    '49': 'Write-off',
    '50': 'Appeal with clinical documentation',
    '55': 'Verify and correct claim data',
    '96': 'Verify benefits, usually write-off',
    '97': 'Appeal if separately billable',
    '109': 'Write off or refer',
    '119': 'Write-off for this period',
    '167': 'Verify dx code, may be correctable',
    '170': 'Retro auth or appeal',
    '197': 'Retro auth or appeal',
    'B7': 'Verify certification',
    'B15': 'Check auth requirements',
    'MA04': 'Submit secondary payer info',

}